---
- name: Arch with Gnome and AMD
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: auto_silent
  gather_facts: true
  roles:
    - reflector
    - base
    - amd
    - git
    - xorg
    - fish
    - fontconfig
    - kitty
    - felix
    - vifm
    - tmux
    - neovim
    - slidev
    - browsers
    - privateinternetaccess
    - ufw
    - pipewire
    - hostname
    - timezone
    - locale
    - network
    - docker
    - gnome
