---
- name: "Laptop installation & configuration"
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: auto_silent
  gather_facts: false
  roles:
    - base
    - intel
    - xorg
    - fish
    - fontconfig
    - kitty
    - felix
    - tmux
    - neovim
    - ufw
    - hostname
    - timezone
    - locale
    - gnome
